### ISSUE TITLE
Change counter-type metrics to be represented as Prometheus counters

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#160]
Currently, all metrics are represented as Prometheus Gauge type metrics.

There are however some metrics whose nature is a counter, that increases monotonically. These are the following metrics:
```
network-physical-adapter-port:
    bytes_sent_count
    bytes_received_count
    packets_sent_count
    packets_received_count
    packets_sent_dropped_count
    packets_received_dropped_count
    packets_sent_discarded_count
    packets_received_discarded_count
    multicast_packets_sent_count
    multicast_packets_received_count
    broadcast_packets_sent_count
    broadcast_packets_received_count
partition-attached-network-interface:
    bytes_sent_count
    bytes_received_count
    packets_sent_count
    packets_received_count
    packets_sent_dropped_count
    packets_received_dropped_count
    packets_sent_discarded_count
    packets_received_discarded_count
    multicast_packets_sent_count
    multicast_packets_received_count
    broadcast_packets_sent_count
    broadcast_packets_received_count
```

They could be represented as Prometheus Count-type metrics.

We are seeking user feedback on this issue. If you have arguments in favor or against such a change, please let us know.

Also, it is not quite clear to me how relevant that is for Prometheus or for using the Prometheus data in Grafana. Is there anything that can be done better if these were Counter type metrics?

**Comment by andy-maier** [comment]
Some articles:
* https://stackoverflow.com/a/58675155/1424462

**Comment by andy-maier** [comment]
PR #161 changes the metric type of some network metrics from gauge to counter. By default (if no comments come in), this will go into 0.8.0.

**Comment by Charles1000Chen** [comment]
I totally agree with using counter type for the monotonically increasing metrics. This is more appropriate.
