### ISSUE TITLE
AttributeError: 'Lpar' object has no attribute 'enable_auto_update'

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#170]
> @vmorris Vance, PR #158 is ready to be tried out. It adds support for several CPC and partition metrics around processors and memory.

I tried testing off master branch today and met the following:

``` 
$ zhmc_prometheus_exporter -c hmccreds.yaml -m metrics.yaml
Error: Error returned from HMC at z15hmc-01.mgmt.upshift.eng.rdu2.redhat.com: 400,7: The following supplied metric group name(s) are invalid: environmental-power-status [POST /api/services/metrics/context]
```

I set `environmental-power-status.fetch` to false and then:

```
$ zhmc_prometheus_exporter -c hmccreds.yaml -m metrics.yaml
Traceback (most recent call last):
  File "/home/fedora/venv-zhmc-prometheus-exporter/bin/zhmc_prometheus_exporter", line 33, in <module>
    sys.exit(load_entry_point('zhmc-prometheus-exporter==0.8.0.dev1', 'console_scripts', 'zhmc_prometheus_exporter')())
  File "/home/fedora/venv-zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 1140, in main
    context, resources = create_metrics_context(
  File "/home/fedora/venv-zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 548, in create_metrics_context
    lpar.enable_auto_update()
AttributeError: 'Lpar' object has no attribute 'enable_auto_update'
```

Any guidance? Thanks!

**Comment by andy-maier** [comment]
@vmorris Vance, on the environmental-power-status metric group:

Support for that metric group was introduced with z15 bundles S20 and H12. On the HMC, there was a regression probably in bundle H18 that caused the metric not to be available anymore; that regression was fixed in bundle H25. You may want to double check if that was the reason.

**Comment by andy-maier** [comment]
@vmorris On the AttributeError: 'Lpar' object has no attribute 'enable_auto_update':

That method comes with zhmcclient 1.0.0. Before zhmcclient 1.0.0 was released to Pypi, the exporter stated a dependency to the topic branch and later to the master branch of zhmcclient that had that method.

Bottom line: Uninstall zhmcclient and the exporter packages, and reinstall the exporter from its master branch. That should pull in the released version 1.0.0 (or 1.0.1) of zhmcclient and the error should be solved. Please let me know whether that worked.

**Comment by vmorris** [comment]
> Support for that metric group was introduced with z15 bundles S20 and H12. On the HMC, there was a regression probably in bundle H18 that caused the metric not to be available anymore; that regression was fixed in bundle H25. You may want to double check if that was the reason.

Thanks for this info. We have a service call out for this machine now so I will include a request to update the bundles.

I reinstalled in a clean environment and now it lgtm!

**Comment by andy-maier** [comment]
Ok, good to hear that it worked. Then I'm closing this issue.
