### ISSUE TITLE
Minimum user configuration for HMC?

### ISSUE THREAD

**Issue by vmorris** [zhmcclient/zhmc-prometheus-exporter#179]
Can you include a minimal user configuration for the HMC? Or if there's a preferred built-in user to create-like, which is it?

Thanks,

**Comment by andy-maier** [comment]
Hi @vmorris , I have put up PR https://github.com/zhmcclient/zhmc-prometheus-exporter/pull/189 for review, which addresses this. I was surprised about the small number of requirements, and must admit that I did not test it out, but gathered them from the docs of the operations that are driven. It would be good if you could actually set up such a restricted user.
