### ISSUE TITLE
Cannot access to zHMC

### ISSUE THREAD

**Issue by garrotemar** [zhmcclient/zhmc-prometheus-exporter#22]
We try connect to zHMC for obtain metrics and can't connect to HMC.
By URL with ip, userid and password I can connect ok, but by the exporter no.
The messages error is:

 $ ./zhmc_prometheus_exporter 
/aplicaciones/prometheus/zhmc/bin/lib64/python3.6/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(yamlcontent)

Time out. Ensure that you have access to the HMC and that you have stored the correct IP address in /etc/zhmc-prometheus-exporter/hmccreds.yaml.

The data in /etc/zhmc-prometheus-exporter/hmccreds.yaml it's ok.

**Comment by leopoldjuergen** [comment]
Did you enable the Webservice API on the HMC ?

See here:
 https://www-01.ibm.com/support/docview.wss?uid=isg2db4805ce05eea3dd85258194006a371e

Search for "Enabling and accessing the API"

**Comment by garrotemar** [comment]
Thanks,  you can close de issue.
