### ISSUE TITLE
Support for additional labels at metric level

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#224]
Right now, the "linecord-XXX-name" metric is commented out in the sample metric definition file, leading to warnings such as:
```
.../zhmc_prometheus_exporter/zhmc_prometheus_exporter.py:727: UserWarning: Skipping metric 'linecord-one-name' of metric group 'environmental-power-status' returned by the HMC that is not defined in the 'metrics' section of metric definition file /opt/zhmc-prometheus-exporter/metrics.yaml
```

The reason this metric is commented out is that its value is an identifier and not an actual metric. It should actually be set as a label on some of the other line cord metrics. However, the ability to add labels only exists at the metric group level.

This item is to add support for labels at the metric level.

This could not only be used for the linecord name metrics, but also for representing other data as labels, such as the status as a string on the has-acceptable-status metric.

**Comment by andy-maier** [comment]
Proposal for representing a mapped value on a metric:
* If a label named "value" is present on an exported metric value, it is used instead of the actual Prometheus floating point value.
* An optional additional label "type" specifies the data type of the value in the "value" label, using "bool", "int", and "str" (default). Float is no needed, because that is the type of the prometheus value without the "value" label.

**Comment by xiqing-zhang** [comment]
Hi Andy, 

Per prometheus data model, the suffix of the metric name describes the unit. e.g.
http_request_duration_seconds
node_memory_usage_bytes
http_requests_total(for a unit-less accumulating count)

In my opinion the metric is usually shown in a panel/dashboard . In the panel, the label can be used to group the metric data. If the label is json or list, it's hard to understand the json or list content at a glance for grouping purpose.
