### ISSUE TITLE
HMC MCL update causes exporter to fail and HMC calls home

### ISSUE THREAD

**Issue by vmorris** [zhmcclient/zhmc-prometheus-exporter#250]
zhmc-prometheus-exporter version: 1.3.2

Recently MCLs were applied to an HMC that I have been collecting metrics from, and the HMC and SE were rebooted a number of times during the update process.

The zhmc-prometheus-exporter did not like this, and ended up in a looping failure state for about 24 hours. I noticed that it was failing then, and restarted the process. It reconnected to the HMC and began functioning properly again.

I was contacted by the admin of the HMC:

> When MCLs are installed the machine is placed in Service Mode which typically blocks many functions.  I am not sure what data collection might be blocked at that point.  When the MCLs are actually installed the primary SE is frequently rebooted.  This means the Primary SE is not available for around 15 to 20 minutes.  Again I have no idea of the response to an inquiry might be during the reboot.
> 
> However, once the MCL activity is finished we are consistently seeing the SE report a refcode indicating that is being bombarded by requests for data from HMC164.
> 
> Since I know the error we can ignore it but it causes the Support Center and PE concern until we investigate because this machine is used for early release MCLs and any error must be vetted before the MCLs can be released to the field.

I am attaching the log from the exporter - can we get better toleration of the maintenance actions on the HMC such that the exporter does not cause call-homes?
[exporter.log](https://github.com/zhmcclient/zhmc-prometheus-exporter/files/10032364/exporter.log)

**Comment by andy-maier** [comment]
Hi Vance. This is definitely a good point. As a long-running process, the exporter is supposed to tolerate this.

**Comment by andy-maier** [comment]
Hi Vance. The error message from the log file "Authentication error when logging on to the HMC at..." and the code line shown in the traceback for line numbers 978 and 137 suggests that this log is from running version 1.0.0 of the exporter.

Can you please double check the exporter version and make sure that 1.3.2 is used, which has several fixes in the area of exception handling and tolerating HMC errors, such as a fix for issue #193 which sounds very much like your case in this issue.

**Comment by vmorris** [comment]
Ah, thank you for the response and suggestion @andy-maier . I thought I WAS on the latest version, as I installed it, but then I took a look at the custom systemd service file that another co-worker created some time ago -- it was using a completely different installation!

We're on the right version now, I'll see if the issue is now gone and report back.

**Comment by andy-maier** [comment]
Ok, I leave the issue open for now.

**Comment by andy-maier** [comment]
@vmorris Can we close this issue?

**Comment by vmorris** [comment]
Yes, thanks Andy.
