### ISSUE TITLE
Dockerimage v1.4.0 is broken / does not start

### ISSUE THREAD

**Issue by nowagn** [zhmcclient/zhmc-prometheus-exporter#258]
After pulling the latest dockerfile and building the image. I receive the following error message after start:

[admin@hostname zhmc_prometheus_exporter]$  podman run -p 9291:9291 zhmcexporter
Traceback (most recent call last):
  File "/usr/local/zhmc_prometheus_exporter.py", line 43, in <module>
    from ._version import __version__
ImportError: attempted relative import with no known parent package

**Comment by nowagn** [comment]
Issue has been solvled by changing line 43 in zhmc_prometheus_exporter.py:

(old) from ._version import __version__ 
(new) from version import __version__

**Comment by andy-maier** [comment]
Hi @nowagn . We are not using the Dockerfile much, so this is a good hint at verifying better that it works. I have opened issue #297 for that.
