### ISSUE TITLE
Changes in HMC, such as the central storage, or MSUs are not automatically applied to zHMC

### ISSUE THREAD

**Issue by dhoppla** [zhmcclient/zhmc-prometheus-exporter#358]
**Describe the bug**
We have changed the MSU value from 12 to 13 for an LPAR on HMC, but unfortunately the new value is not displayed in the zHMC.  In another LPAR we have enlarged the central memory from 8192 to 9216, this value is also not displayed in the zHMC.
In both cases, only the old value is displayed.

zhmc_partition_current_central_memory_mib{cpc="XXXX",hmc="XXXXHMC",partition="XXXXCF36",pod="mypod"} 8192.0
zhmc_partition_defined_capacity_msu_per_hour{cpc="XXXX",hmc="XXXXHMC",partition="XXXXXXXX",pod="mypod"} 12.0

**Expected behavior**
It would be nice that these changes could be automatically displayed in the zHMC.

**To Reproduce**
We changed the MSU value on HMC from 12 to 13 and also the central memory vom 8192MB to 9216 MB

**Environment information**
* Output of `zhmc_prometheus_exporter --version`: 
* zhmc_prometheus_exporter version: 1.5.0.dev1
  zhmcclient version: 1.9.1
* HMC version:
* 2.15.0

**Command output**
<-- Relevant parts of the command output. If possible, with '-vv'. -->

**Log file**
<-- If possible, attach a log file generated with '--log-comp all=debug --log exporter.log'. -->

**Comment by dhoppla** [comment]
Hi,
do they need further documentation ?

**Comment by andy-maier** [comment]
Hello @dhoppla - the hmc.log file does not contain much useful information for this issue, but I can try to reproduce it locally.

**Comment by andy-maier** [comment]
I started analyzing the issue.

* For the `zhmc_partition_defined_capacity_msu_per_hour` metric, the reason it is not changing is that the corresponding property `defined-capacity` on the "Logical Partition" object does not support property change notifications. The zhmc exporter subscribes for property change notifications for all of its metrics that are resource-based. These are the metrics in the metric definition file that have "type: resource". So the exporter relies on property change notifications being sent from the HMC to the exporter, whenever the value changes. Apparently we defined at least this one metric without double checking that it actually supports property change notfications. I will need to check this for all other resource-based metrics, and then figure out whether implementing a circumvention makes sense (the only circumvention I know is to fetch the LPAR properties when Prometheus asks for updated metrics, which will make the response time to Prometheus larger. Stay tuned.

* For the `zhmc_partition_current_central_memory_mib` metric: This metric supports property change notifications, but I did not find a way to change the central storage on an LPAR that is operating. How did you change the central storage? Did you change it in the image activation profile and then re-activated the LPAR?

* For the `zhmc_partition_cp_current_processing_weight` metric: That metric is not representing the defined capacity, but the relative processing weight. Its value has the unit of a weight relative to all other shared LPARs. The defined capacity has  an MSU/h unit. If the two values are the same then that's a coincidence, IMO. I have to admit that I'm not a classic mode expert though, so you can possibly educate me on why you expected the current weight to change.

**Comment by dhoppla** [comment]
Hi,
we change the central storage in the image activation profile and re-activated the LPAR.

We get many orders from our customers to change the current MSU settings during operation. So it would be nice to see the current values.

**Comment by andy-maier** [comment]
Sorry for the delay. I am resuming the work on this issue now.

**Comment by andy-maier** [comment]
I have investigated the resource properties that are shown as metrics by the zhmc prometheus exporter regarding whether they support property change notifications, and the following list of properties can change, but does not support change notifications:

LPAR properties (classic mode):
- description
- defined-capacity    <- used for zhmc_partition_defined_capacity_msu_per_hour
- number-general-purpose-processors
- number-reserved-general-purpose-processors
- current-processing-weight-capped
- number-ifl-processors
- number-reserved-ifl-processors
- current-ifl-processing-weight-capped
- number-icf-processors
- number-reserved-icf-processors
- current-cf-processing-weight-capped
- number-ziip-processors
- number-reserved-ziip-processors
- current-ziip-processing-weight-capped
- initial-aap-processing-weight
- minimum-aap-processing-weight
- maximum-aap-processing-weight
- current-aap-processing-weight
- absolute-aap-capping
- initial-aap-processing-weight-capped
- current-aap-processing-weight-capped
- initial-cbp-processing-weight
- minimum-cbp-processing-weight
- maximum-cbp-processing-weight
- current-cbp-processing-weight
- absolute-cbp-capping
- initial-cbp-processing-weight-capped
- current-cbp-processing-weight-capped
- storage-central-allocation      <- used for zhmc_partition_current_central_memory_mib
- storage-expanded-allocation
- initial-vfm-storage
- maximum-vfm-storage
- current-vfm-storage

CPC properties:
- processor-count-aap
- processor-count-cbp
- processor-count-service-assist
- processor-count-defective
- processor-count-spare
- storage-hardware-system-area
- storage-customer
- storage-customer-central
- storage-customer-expanded
- storage-customer-available
- storage-vfm-increment-size
- storage-vfm-total

**Comment by andy-maier** [comment]
The measurements are encouraging, but not encouraging enough to fetch these properties synchronously when Prometheus requests metrics from the exporter. I guess we need to build an async mechanism for that.

**Comment by andy-maier** [comment]
I have started implementing support for fetching these properties in the background. See PR #469

**Comment by andy-maier** [comment]
@dhoppla 
PR https://github.com/zhmcclient/zhmc-prometheus-exporter/pull/469 is ready for use.

You can try it out by installing it from the branch of that PR:
```
pip install zhmcclient@git+https://github.com/zhmcclient/zhmc-prometheus-exporter.git@andy/fetch-properties
```
Please make sure that you use the new metric definition file: 
https://github.com/zhmcclient/zhmc-prometheus-exporter/blob/andy/fetch-properties/examples/metrics.yaml
