### ISSUE TITLE
ZHMC starting message in log shouldn't be WARNING.

### ISSUE THREAD

**Issue by Charles1000Chen** [zhmcclient/zhmc-prometheus-exporter#394]
**Describe the bug**

When the zhmc prometheus exporter starts, it prints the following warning message in log:

2023-10-24 06:33:10+0000 **WARNING** zhmcexporter: ---------------- zhmc_prometheus_exporter started ----------------

**Expected behavior**

The zhmc prometheus exporter starting message should be "**INFO**", not "**WARNING**"

**To Reproduce**
N/A

**Environment information**
* Output of `zhmc_prometheus_exporter --version`:
1.5.0.dev1
* HMC version:
N/A

**Command output**
N/A

**Log file**
N/A

**Comment by Charles1000Chen** [comment]
https://github.com/zhmcclient/zhmc-prometheus-exporter/pull/396

**Comment by andy-maier** [comment]
The reason for setting this to WARNING level was to ensure that it is created most of the time. The message itself certainly does not have a warning semantics, so I'm ok with the change.
