### ISSUE TITLE
Unhandled wsgiref exception in log

### ISSUE THREAD

**Issue by Charles1000Chen** [zhmcclient/zhmc-prometheus-exporter#397]
**Describe the bug**
The following error from the wsgiref package in ZHMC prometheus exporter log is unhandled:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 288, in write
    self.send_headers()
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 346, in send_headers
    self.send_preamble()
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 268, in send_preamble
    self._write(
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 467, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)
```

**Expected behavior**
The wsgiref exception should be catched by zhmc prometheus exporter and output understandable error message.

**To Reproduce**
<-- Describe the steps to reproduce the behavior. -->

**Environment information**
* Output of `zhmc_prometheus_exporter --version`:
1.5.0.dev1
* HMC version:
N/A

**Command output**
<-- Relevant parts of the command output. If possible, with '-vv'. -->

**Log file**
<-- If possible, attach a log file generated with '--log-comp all=debug --log exporter.log'. -->

**Comment by Charles1000Chen** [comment]
The SSLEOFError exception needs be handled when call the "start_http_server" function.

**Comment by andy-maier** [comment]
@Charles1000Chen The code already catches `ssl.SSLError` when raised by the "start_http_server" function, because it is a subclass of `IOError`: https://github.com/zhmcclient/zhmc-prometheus-exporter/blob/master/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py#L1871

I think what probably happens is that the ssl exception is raised in the thread that is started.

**Comment by Charles1000Chen** [comment]
@andy-maier I basically agree with you. Currently, the error can be seen in my test every once in a while. Could we catch the `Exception` as well and put the update in the version 1.5.0b2, so that I'll test it in my environment to see if any difference?

**Comment by andy-maier** [comment]
@Charles1000Chen Yes, i can open up the type of exceptions from `IOError` to `Exception` to make sure we catch everything, and build a new beta version.

**Comment by andy-maier** [comment]
[Beta version 1.5.0b3](https://github.com/zhmcclient/zhmc-prometheus-exporter/releases/tag/1.5.0b3) has been released, with the changes to the exception handling.

**Comment by andy-maier** [comment]
I am closing his issue and will release the official 1.5.0 version today. If the problem re-occurs, please reopen this issue or open a new issue.
