### ISSUE TITLE
Got tons of Jinja2 expression messages after the exporter started

### ISSUE THREAD

**Issue by cheeye** [zhmcclient/zhmc-prometheus-exporter#488]
**Describe the bug**
Got tons of messages like below: 
```
Ignoring label 'value' on metric with exporter name 'storage_groups' due to error in rendering the Jinja2 expression in its value: KeyError: '/api/storage-groups/646e5dd6-ba10-11eb-a480-00106f23b391'
```

**To Reproduce**
Starting the exporter.

**Environment information**
* Output of `zhmc_prometheus_exporter --version`: 
```
zhmc_prometheus_exporter version: 1.5.0
zhmcclient version: 1.14.0
```

* HMC version:  2.15.0. Driver 41C

**Command output**
zhmc_prometheus_exporter

**Comment by andy-maier** [comment]
@cheeye These warnings should not affect the function of the exporter. I will look into it.

**Comment by andy-maier** [comment]
@cheeye provided zhmc exporter log files to me. Unfortunately, the log records in there are not sufficient for me to understand the issue.

I have added additional details when this happens, that are printed on the output and also put into the zhmc exporter log. That is in PR #498 and will be in the upcoming version 1.6.0 (to be released soon).

**Comment by andy-maier** [comment]
I am closing this ticket.
Version 1.6.0 of the zhmc exporter has been released today. It produces debug output (to both standard out and to the log file) in case the issue with the Jinja2 expressions happens again. In case it happens again, please open a new issue and provide the complete log file with `--log-comp hmc=debug` set.
