### ISSUE TITLE
how to limit the log size 

### ISSUE THREAD

**Issue by fulwang** [zhmcclient/zhmc-prometheus-exporter#528]
hello,

I'm running zhmc-prometheus-exporter inside a container managed by podman.

#podman run -itd --rm -v /opt/zhmcexporter:/root/myconfig -p 9291:9291 --name zhmcexporter zhmcexporter:latest -c /root/myconfig/hmccreds.yaml -v

and just found the file "/var/lib/containers/storage/overlay-containers/a3365f0168372b863449f814d2dcff3dbdef0948f40913176925b6d4a74a9aaa/userdata/ctr.log" getting too large after several days, the biggest one is the ctr.log reched 40GB now. is there any method can control the log file size or rotate it?

[root@lpar27 userdata]# 
[root@lpar27 userdata]# ls -lh 
total 41G
drwxr-xr-x 2 root root   6 Jun 24 18:44 artifacts
srwx------ 1 root root   0 Jun 24 18:44 attach
-rw-r--r-- 1 root root 12K Jun 24 18:44 config.json
prw-r----- 1 root root   0 Jun 24 18:44 ctl
-rw------- 1 root root 41G Jun 27 11:56 ctr.log
drwxr-xr-x 2 root root   6 Jun 24 18:44 secrets
drwxrwxrwt 2 root root  40 Jun 24 18:44 shm
prw-r----- 1 root root   0 Jun 24 18:44 winsz
[root@lpar27 userdata]#

**Comment by andy-maier** [comment]
@fulwang Hello Fu Long. Sorry for the delay in responding.

From what you posted, I see that you are using the `-v` option one time, meaning you are running at verbosity level 1, and that you are not enabling logging (no `--log` option).

With verbosity level 1, the standard output should not grow over time. The last line shown should be "Exporter is up and running on port 9291".

Is your `ctr.log` file the terminal output of the exporter?

Can you please send me the file (or the first few MB from it) on the internal #zhmcclient Slack channel?

**Comment by fulwang** [comment]
Thanks @andy-maier,

I have confirmed that "ctr.log" is console log of the container, so i set a limit on the podman config file which when the limit reached the log will be truncated.

**Comment by andy-maier** [comment]
After chatting with Fu Long privately, it turned out that the `-v` option had been specified two times, so the exporter was running at verbosity level 2. Where it does in fact produce continuous output.

I will put an according warning into the docs.
