### ISSUE TITLE
Need help to run prometheus exporter on z16 CECs

### ISSUE THREAD

**Issue by Nidhigupta517** [zhmcclient/zhmc-prometheus-exporter#529]
Hi All, 

I am trying use prometheus exporter on z16 CECs. As per the process, we should have 3 files. We have got the cert file, CA-cert file but not getting key file. I have checked on HMCs but there is no option to export SSH key file. Could you please guide me on How do I export the key file?

**Comment by andy-maier** [comment]
You need to distinguish two communicaiton paths:

* Communication between the exporter and the HMC
  At the level of the TLS protocol, the exporter is in a client role in this communication. Therefore you only need 1 file for that, and that is the CA certificate used to validate the server certificate that was loaded into the HMC. You specify that in the `metrics.verify_cert` property in the HMC credentials file of the exporter. See https://zhmc-prometheus-exporter.readthedocs.io/en/stable/usage.html#hmc-certificate

* Communication between Prometheus and the exporter
  At the level of the TLS protocol, the exporter is in a server role in that communication. Therefore you need 3 files for that (server key, server certificate, CA certificate). You need to generate the server key and server certificate file yourself, using the appropriate process for the CA you are choosing. You specify these files in the `prometheus.server_cert_file/server_key_file/ca_cert_file` properties in the HMC credentials file of the exporter. See https://zhmc-prometheus-exporter.readthedocs.io/en/stable/usage.html#communication-with-prometheus

**Comment by andy-maier** [comment]
@Nidhigupta517 I have put up PR #533 to improve the section about the HMC certificate.
